# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"QuantumOptimizer": "01_optimization.ipynb",
         "SUPPORTED_TASKS": "01_optimization.ipynb",
         "DEFAULT_LOCAL": "01_optimization.ipynb",
         "add_metrics_to_log": "02_utils.ipynb",
         "log_to_message": "02_utils.ipynb",
         "ProgressBar": "02_utils.ipynb"}

modules = ["core.py",
           "optimization.py",
           "utils.py"]

doc_url = "https://amaiya.github.io/quixotic/"

git_url = "https://github.com/amaiya/quixotic/tree/main/"

def custom_doc_links(name): return None
